name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Build the project
      run: xcodebuild -workspace EpamTest.xcodeproj -scheme EpamTest -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Run tests
      run: xcodebuild test -workspace EpamTest.xcodeproj -scheme EpamTest -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
